Supplier.create!([
  {name: "Bob", email: "bob@gmail.com", phone_number: "4155555555"},
  {name: "Ernest", email: "e@gmail.com", phone_number: "415765555"}
])

Book.create!([
  {name: "The Complete Guide to Rat Training", author: "Debbie Ducommun", description: "The Complete Guide to Rat Training teaches you how to have fun and enhance the relationship you share with your pet rat. The step-by-step format thoroughly and concisely covers a variety of training topics, including positive reinforcement, clicker training, basic and advanced trick training, and how to set up games and science projects.", stock: nil, image: nil, price: nil, supplier_id: 1},
  {name: "Yes Please!", author: "Amy Poehler", description: "Do you want to get to know the woman we first came to love on Comedy Central's Upright Citizens Brigade? Do you want to spend some time with the lady who made you howl with laughter on Saturday Night Live, and in movies like Baby Mama, Blades of Glory, and They Came Together? Do you find yourself daydreaming about hanging out with the actor behind the brilliant Leslie Knope on Parks and Recreation? Did you wish you were in the audience at the last two Golden Globes ceremonies, so you could bask in the hilarity of Amy's one-liners?", stock: nil, image: "https://images-na.ssl-images-amazon.com/images/I/51JeCzV8CoL._AC_US500_FMwebp_QL65_.jpg", price: "9.0", supplier_id: 1},
  {name: "The Will Parrots on Telegraph Hill", author: "Mark Bittner", description: "Like a lot of young people in the 1970s, Mark Bittner took the path of the “dharma bum.” When the counterculture faded, Mark held on, seeking shelter in the nooks and crannies of San Francisco’s fabled bohemian neighborhood, North Beach. While living on the eastern slope of Telegraph Hill, he made a magical discovery: a flock of wild parrots.", stock: nil, image: "https://images-na.ssl-images-amazon.com/images/I/51%2BS-UMCqEL._SX321_BO1,204,203,200_.jpg", price: "11.2", supplier_id: 2},
  {name: "Why we sleep", author: "Matthew Walker", description: "How a good night's shut-eye can make us cleverer, more attractive, slimmer, happier, healthier, and ward off cancer", stock: nil, image: "http://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1493492341i/34466963._SR1200,630_.jpg", price: "24.0", supplier_id: 2},
  {name: "The Life-Changing Magic of Tidying up", author: "Marie Kondo", description: "Best-selling guide to decluttering your home from Japanese cleaning consultant Marie Kondo takes readers step-by-step through her revolutionary KonMari Method for simplifying, organizing, and storing", stock: nil, image: "https://tse4.mm.bing.net/th?id=OIP.NajjQDODrHCo9OnBiOZxcwHaHa&pid=Api", price: "11.99", supplier_id: 2},
  {name: "Musashi: An Epic Novel of the Samurai Era", author: "Eiji Yoshikawa", description: "Miyamoto Musashi was the child of an era when Japan was emerging from decades of civil strife. Lured to the great Battle of Sekigahara in 1600 by the hope of becoming a samurai--without really knowing what it meant--he regains consciousness after the battle to find himself lying defeated, dazed and wounded among thousands of the dead and dying. On his way home, he commits a rash act, becomes a fugitive and brings life in his own village to a standstill--until he is captured by a weaponless Zen monk.", stock: nil, image: "https://prodimage.images-bn.com/pimages/9781568364513_p0_v4_s600x595.jpg", price: "9.5", supplier_id: 1},
  {name: "The Tao of Pooh", author: "Benjamin Hoff", description: "The how of Pooh? The Tao of who? The Tao of Pooh!?! In which it is revealed that one of the world's great Taoist masters isn't Chinese--or a venerable philosopher--but is in fact none other than that effortlessly calm, still, reflective bear. A. A. Milne's Winnie-the-Pooh! While Eeyore frets, and Piglet hesitates, and Rabbit calculates, and Owl pontificates, Pooh just is.", stock: nil, image: "https://improvmantra.files.wordpress.com/2011/07/tao-of-pooh.jpg", price: "15.0", supplier_id: 1}
])

